import type { BMWPart } from "./BMWPart" // Assuming BMWPart is defined in another file

export const COMPREHENSIVE_BMW_PARTS: BMWPart[] = [
  // ===== UNIVERSAL OEM PARTS (Compatible with ALL BMWs) =====

  // Universal Oil Filters
  {
    id: "universal-oil-filter-standard",
    partNumber: "11427566300",
    name: "Universal Oil Filter",
    description: "OEM oil filter compatible with all BMW engines",
    category: "Engine",
    subcategory: "Filters",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 29.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Air Filters
  {
    id: "universal-air-filter",
    partNumber: "13717566016",
    name: "Universal Air Filter",
    description: "OEM air filter for all BMW models",
    category: "Engine",
    subcategory: "Filters",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 34.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Cabin Filters
  {
    id: "universal-cabin-filter",
    partNumber: "64319216588",
    name: "Universal Cabin Air Filter",
    description: "OEM cabin air filter for all BMW models",
    category: "Interior",
    subcategory: "Climate Control",
    compatibleChassis: ["ALL"],
    price: 39.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Brake Components
  {
    id: "universal-brake-pads-front",
    partNumber: "34116794300",
    name: "Universal Front Brake Pads",
    description: "OEM front brake pads compatible with all BMW models",
    category: "Brakes",
    subcategory: "Brake Pads",
    compatibleChassis: ["ALL"],
    price: 89.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-brake-pads-rear",
    partNumber: "34216794301",
    name: "Universal Rear Brake Pads",
    description: "OEM rear brake pads compatible with all BMW models",
    category: "Brakes",
    subcategory: "Brake Pads",
    compatibleChassis: ["ALL"],
    price: 79.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-brake-rotors-front",
    partNumber: "34116855000",
    name: "Universal Front Brake Rotors",
    description: "OEM front brake rotors for all BMW models",
    category: "Brakes",
    subcategory: "Brake Rotors",
    compatibleChassis: ["ALL"],
    price: 159.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-brake-rotors-rear",
    partNumber: "34216855001",
    name: "Universal Rear Brake Rotors",
    description: "OEM rear brake rotors for all BMW models",
    category: "Brakes",
    subcategory: "Brake Rotors",
    compatibleChassis: ["ALL"],
    price: 139.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Suspension Components
  {
    id: "universal-shock-absorber-front",
    partNumber: "31316789000",
    name: "Universal Front Shock Absorber",
    description: "OEM front shock absorber for all BMW models",
    category: "Suspension",
    subcategory: "Shock Absorbers",
    compatibleChassis: ["ALL"],
    price: 199.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-shock-absorber-rear",
    partNumber: "33526789001",
    name: "Universal Rear Shock Absorber",
    description: "OEM rear shock absorber for all BMW models",
    category: "Suspension",
    subcategory: "Shock Absorbers",
    compatibleChassis: ["ALL"],
    price: 189.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-control-arm-front",
    partNumber: "31126789100",
    name: "Universal Front Control Arm",
    description: "OEM front control arm for all BMW models",
    category: "Suspension",
    subcategory: "Control Arms",
    compatibleChassis: ["ALL"],
    price: 249.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Engine Components
  {
    id: "universal-spark-plugs",
    partNumber: "12120037244",
    name: "Universal Spark Plugs (Set of 4)",
    description: "OEM spark plugs compatible with all BMW engines",
    category: "Engine",
    subcategory: "Ignition",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 79.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-ignition-coils",
    partNumber: "12137594937",
    name: "Universal Ignition Coil",
    description: "OEM ignition coil for all BMW engines",
    category: "Engine",
    subcategory: "Ignition",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 89.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-thermostat",
    partNumber: "11537549476",
    name: "Universal Thermostat",
    description: "OEM thermostat for all BMW engines",
    category: "Engine",
    subcategory: "Cooling",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 69.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-water-pump",
    partNumber: "11517586925",
    name: "Universal Water Pump",
    description: "OEM water pump for all BMW engines",
    category: "Engine",
    subcategory: "Cooling",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 189.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Transmission Components
  {
    id: "universal-transmission-filter",
    partNumber: "24117571227",
    name: "Universal Transmission Filter",
    description: "OEM transmission filter for all BMW transmissions",
    category: "Transmission",
    subcategory: "Filters",
    compatibleChassis: ["ALL"],
    price: 49.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-transmission-fluid",
    partNumber: "83222405966",
    name: "Universal Transmission Fluid",
    description: "OEM transmission fluid for all BMW transmissions",
    category: "Transmission",
    subcategory: "Fluids",
    compatibleChassis: ["ALL"],
    price: 29.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Electrical Components
  {
    id: "universal-battery",
    partNumber: "61217555719",
    name: "Universal Battery",
    description: "OEM battery for all BMW models",
    category: "Electrical",
    subcategory: "Battery",
    compatibleChassis: ["ALL"],
    price: 199.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-alternator",
    partNumber: "12317508003",
    name: "Universal Alternator",
    description: "OEM alternator for all BMW models",
    category: "Electrical",
    subcategory: "Charging",
    compatibleChassis: ["ALL"],
    price: 399.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-starter",
    partNumber: "12417508178",
    name: "Universal Starter Motor",
    description: "OEM starter motor for all BMW models",
    category: "Electrical",
    subcategory: "Starting",
    compatibleChassis: ["ALL"],
    price: 349.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Body & Exterior
  {
    id: "universal-headlight-bulb",
    partNumber: "63217217509",
    name: "Universal Headlight Bulb",
    description: "OEM headlight bulb for all BMW models",
    category: "Body & Exterior",
    subcategory: "Lighting",
    compatibleChassis: ["ALL"],
    price: 39.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-tail-light-bulb",
    partNumber: "63217217510",
    name: "Universal Tail Light Bulb",
    description: "OEM tail light bulb for all BMW models",
    category: "Body & Exterior",
    subcategory: "Lighting",
    compatibleChassis: ["ALL"],
    price: 24.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-side-mirror",
    partNumber: "51167203204",
    name: "Universal Side Mirror",
    description: "OEM side mirror for all BMW models",
    category: "Body & Exterior",
    subcategory: "Mirrors",
    compatibleChassis: ["ALL"],
    price: 189.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Interior Components
  {
    id: "universal-floor-mats",
    partNumber: "51472414219",
    name: "Universal Floor Mats (Set of 4)",
    description: "OEM floor mats for all BMW models",
    category: "Interior",
    subcategory: "Floor Mats",
    compatibleChassis: ["ALL"],
    price: 129.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-seat-covers",
    partNumber: "52107414220",
    name: "Universal Seat Covers",
    description: "OEM seat covers for all BMW models",
    category: "Interior",
    subcategory: "Seating",
    compatibleChassis: ["ALL"],
    price: 199.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // Universal Maintenance Items
  {
    id: "universal-engine-oil",
    partNumber: "83212365950",
    name: "Universal Engine Oil (5W-30)",
    description: "OEM engine oil for all BMW engines",
    category: "Engine",
    subcategory: "Fluids",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 49.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-coolant",
    partNumber: "83192211191",
    name: "Universal Coolant",
    description: "OEM coolant for all BMW engines",
    category: "Engine",
    subcategory: "Fluids",
    compatibleChassis: ["ALL"],
    compatibleEngines: ["ALL"],
    price: 34.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  {
    id: "universal-brake-fluid",
    partNumber: "83132405977",
    name: "Universal Brake Fluid",
    description: "OEM brake fluid for all BMW models",
    category: "Brakes",
    subcategory: "Fluids",
    compatibleChassis: ["ALL"],
    price: 19.99,
    availability: "in-stock",
    oem: true,
    aftermarket: false,
    brand: "BMW",
    imageUrl: "/placeholder.svg?height=200&width=200",
  },

  // ===== EXISTING SPECIFIC PARTS =====

  // Add specific parts here if needed
]
